### ISSUE TITLE
Header appears over content on mobile

### ISSUE THREAD

**Issue by SimplyCodin** [Disconnect24/disconnect24.xyz#5]
[Example](https://i.imgur.com/hprMqGB.png)

**Comment by SpikeyScout** [comment]
Happens on iOS too (what did i think lol)
[On iOS](https://cdn.discordapp.com/attachments/376510787851649034/406589320921743362/image.png)

**Comment by spotlightishere** [comment]
Can confirm issue exists. It's up for grabs, anyone wanna take a stab? ;P

**Comment by SimplyCodin** [comment]
I created a PR a while ago that fixes this issue in the style of sass already written
