### ISSUE TITLE
index - it'S yOur noT yoU're rEE

### ISSUE THREAD

**Issue by DarkPhoenix10** [Disconnect24/disconnect24.xyz#6]
![image](https://user-images.githubusercontent.com/13627433/35293887-07d0fa12-006d-11e8-9410-899756b63cc8.png)
**AAAAAAAAAAAAAAAAAAAAAa**

**Comment by DarkPhoenix10** [comment]
REEEEEEEEEEEEEEEEEEEEEE

**Comment by iDroid27210** [comment]
As a baguette-land inhabitant I have been... terrified to see that.
Governments must take actions to help the world in that crisis !!
#YourAndNotYouRe

**Comment by spotlightishere** [comment]
As an oil land inhabitant I deeply apologise for the issue and will be taking action against the person who did this.


~~whoops lol~~

On January 23, 2018 7:34:20 PM UTC, iDroid <notifications@github.com> wrote:
>As a baguette-land inhabitant I have been... terrified to see that.
>Governments must take actions to help the world in that crisis !!
>#YourAndNotYouRe
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Disconnect24/disconnect24.xyz/issues/6#issuecomment-359904256

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DarkPhoenix10** [comment]
~~**YOUR** bad at english~~

**Comment by DismissedGuy** [comment]
That might be but your badder at English than I am.

**Comment by spotlightishere** [comment]
Now now, both of you can be bad at English.
